### ISSUE TITLE
module 'rest_framework_docs'

### ISSUE THREAD

**Issue by ahmedcharef** [electrocoder/iotdashboard#12]
Hello,your project is awesome !

I got this error after I run:"python manage.py runserver"

`django.core.exceptions.ImproperlyConfigured: The included URLconf '<module 'rest_framework_docs' from '/usr/local/lib/python2.7/dist-packages/rest_framework_docs/__init__.pyc'>' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.`

Is there any solution for this?

PS:I have installed this too 
"pip install django-rest-framework-docs"

**Comment by electrocoder** [comment]
Updated project

**Comment by electrocoder** [comment]
Updated project
