### ISSUE TITLE
Payment Validasyon eksik

### ISSUE THREAD

**Issue by dogukankotan** [electrocoder/iotdashboard#4]
https://iothook.com/tr/payment/credit-card/  bu adreste ödeme yap dediğimde kredi kartı girmeden "Teşekkürler. Kredi kartı eklendi." diyor. Validate etmeli.

**Comment by electrocoder** [comment]
İot dashboard adresi http://ihook.xyz/ dır. Buradan test edebilirsiniz

**Comment by electrocoder** [comment]
İot dashboard adresi http://ihook.xyz/ dır.
