### ISSUE TITLE
Python 3 Django 1.10.1 ve 1.9.9 problemi

### ISSUE THREAD

**Issue by mesebilisim** [electrocoder/iotdashboard#6]
Python 3 de çalışırken Mac OS X Yosemite üzerinde Django 1.10.1 ve 1.9.9 da hata veriyor.
File "python3/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)

**Comment by electrocoder** [comment]
Sorunun Mac OS X deki dil ayarları ile alakalı olduğu öğrenildi. 
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
ile çözüldü.
[https://goo.gl/Mtq24d](https://goo.gl/Mtq24d)  kısa not eklendi.
